# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261a25edefc7be5ddf70acb4ee25d0eae546f403977a33e11fd81844d988deb22a9dfe48fdda1cb68f67a108c754d25a8a309f108fc0732d75f80e8aacd78824

test:
  secret_key_base: a76b0cd6b12f42615aac4ffaad553f76f0fa0d7af66e22fa365176951e716c06a8629295b311228b23e26d73cc9e01669a32aa388b589a084d49f03c15ea9ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
